"""
pdf_export.py
-------------
Builds a PDF of a full analysis session: the brief, its verification results,
the sources, and the follow-up Q&A transcript.

Uses fpdf2 — pure Python, no system dependencies, Docker-friendly.
"""

import re
from fpdf import FPDF
from fpdf.enums import XPos, YPos   # for the modern line-break syntax


def _clean(text: str) -> str:
    """Strip Markdown and non-Latin-1 chars (fpdf2 core fonts are Latin-1 only)."""
    if not text:
        return ""
    text = re.sub(r"^#{1,6}\s*", "", text, flags=re.MULTILINE)   # headings
    text = text.replace("**", "").replace("*", "").replace("`", "")
    replacements = {"–": "-", "—": "-", "’": "'", "‘": "'", "“": '"', "”": '"', "•": "-", "→": "->"}
    for bad, good in replacements.items():
        text = text.replace(bad, good)
    return text.encode("latin-1", "ignore").decode("latin-1")


class BriefPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 58, 138)
        self.cell(0, 8, "Clinical Decision Brief", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by Cheiron Demo  ·  Page {self.page_no()}", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(30, 58, 138)
        self.ln(2)
        self.cell(0, 8, _clean(title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(0, 0, 0)

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 5, _clean(text))
        self.ln(1)


def build_pdf(query: str, brief: str, score: dict, sources: list, conversation: list) -> bytes:
    """Assemble the full session PDF and return it as raw bytes."""
    pdf = BriefPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, _clean(f"Query: {query}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    pdf.body_text(brief)

    pdf.section_title("Verification")
    valid = ", ".join(score.get("valid_ids", [])) or "none"
    invalid = ", ".join(score.get("invalid_ids", [])) or "none"
    pdf.body_text(
        f"Citation accuracy: {score.get('accuracy_percent', 0)}%\n"
        f"Valid citations: {valid}\n"
        f"Fabricated citations: {invalid}\n"
        f"Weighted score: {score.get('points', 0)} (valid +1, fabricated -5)"
    )

    pdf.section_title("Sources")
    for s in sources:
        if s.get("nct_id"):
            pdf.body_text(f"{s['nct_id']} - {s.get('title','')}\n{s.get('url','')}")

    if conversation:
        pdf.section_title("Follow-up Q&A")
        for turn in conversation:
            who = "Q" if turn["role"] == "user" else "A"
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 5, f"{who}:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.body_text(turn["content"])

    return bytes(pdf.output())


if __name__ == "__main__":
    fake_score = {"accuracy_percent": 100, "valid_ids": ["NCT01"], "invalid_ids": [], "points": 1}
    fake_sources = [{"nct_id": "NCT01", "title": "Test Trial", "url": "https://example.com"}]
    fake_convo = [
        {"role": "user", "content": "Which is most advanced?"},
        {"role": "assistant", "content": "NCT01 is Phase 3 [NCT01]."},
    ]
    data = build_pdf("semaglutide", "# Snapshot\nThis is a test brief [NCT01].",
                     fake_score, fake_sources, fake_convo)
    with open("test_output.pdf", "wb") as f:
        f.write(data)
    print(f"Wrote test_output.pdf ({len(data)} bytes)")